DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS monthly_balances CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS plant_goals CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);
 
CREATE TABLE accounts (
  id SERIAL PRIMARY KEY NOT NULL,
  type VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  current_balance INTEGER NOT NULL
)

CREATE TABLE transactions (
  id SERIAL PRIMARY KEY NOT NULL,
  date 
  amount INTEGER
  category_id 
  credit BOOLEAN

)

CREATE TABLE monthly_balances (
  id SERIAL PRIMARY KEY NOT NULL,

)

CREATE TABLE categories (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
)

CREATE TABLE plant_goals (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
)